CREATE TABLE IF NOT EXISTS PUBLIC.PUBLIC.PESSOA (
	ID BIGINT NOT NULL IDENTITY,
	NOME VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(30),
	CPF VARCHAR(20) NOT NULL,
	SEXO VARCHAR(20),
	DATA_NASC DATE NOT NULL,
	NATURALIDADE VARCHAR(20),
	NACIONALIDADE VARCHAR(20),
	CONSTRAINT SYS_PK_10092 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX  IF NOT EXISTS SYS_IDX_SYS_PK_10092_10096 ON PUBLIC.PUBLIC.PESSOA (ID);